version: '3.8'

services:
  # Application with Nginx and PHP-FPM
  app:
    image: cygnuzerp/app:latest
    container_name: cygnuz_app
    restart: always
    environment:
      APP_NAME: "${APP_NAME}"
      APP_ENV: production
      APP_KEY: "${APP_KEY}"
      APP_DEBUG: "false"
      APP_URL: "${APP_URL}"
      DB_CONNECTION: mysql
      DB_HOST: "${DB_HOST}"
      DB_PORT: "${DB_PORT:-3306}"
      DB_DATABASE: "${DB_DATABASE}"
      DB_USERNAME: "${DB_USERNAME}"
      DB_PASSWORD: "${DB_PASSWORD}"
      CACHE_DRIVER: redis
      QUEUE_CONNECTION: redis
      SESSION_DRIVER: redis
      REDIS_HOST: redis
      REDIS_PORT: 6379
      MAIL_MAILER: "${MAIL_MAILER}"
      MAIL_HOST: "${MAIL_HOST}"
      MAIL_PORT: "${MAIL_PORT}"
      MAIL_USERNAME: "${MAIL_USERNAME}"
      MAIL_PASSWORD: "${MAIL_PASSWORD}"
      MAIL_ENCRYPTION: "${MAIL_ENCRYPTION}"
      MAIL_FROM_ADDRESS: "${MAIL_FROM_ADDRESS}"
    ports:
      - "${APP_PORT:-80}:80"
    volumes:
      - app_storage:/var/www/html/storage
      - app_logs:/var/www/html/storage/logs
    depends_on:
      - redis
    networks:
      - cygnuz_network
    deploy:
      resources:
        limits:
          cpus: '2'
          memory: 2G
        reservations:
          cpus: '1'
          memory: 1G

  # Redis Cache
  redis:
    image: redis:7-alpine
    container_name: cygnuz_redis
    restart: always
    command: redis-server --appendonly yes --requirepass "${REDIS_PASSWORD}"
    volumes:
      - redis_data:/data
    networks:
      - cygnuz_network
    deploy:
      resources:
        limits:
          cpus: '0.5'
          memory: 512M

  # Queue Worker
  queue:
    image: cygnuzerp/app:latest
    container_name: cygnuz_queue
    restart: always
    command: php artisan queue:work --sleep=3 --tries=3 --max-time=3600
    environment:
      APP_ENV: production
      DB_CONNECTION: mysql
      DB_HOST: "${DB_HOST}"
      DB_PORT: "${DB_PORT:-3306}"
      DB_DATABASE: "${DB_DATABASE}"
      DB_USERNAME: "${DB_USERNAME}"
      DB_PASSWORD: "${DB_PASSWORD}"
      REDIS_HOST: redis
      REDIS_PORT: 6379
      REDIS_PASSWORD: "${REDIS_PASSWORD}"
    volumes:
      - app_storage:/var/www/html/storage
    depends_on:
      - redis
    networks:
      - cygnuz_network
    deploy:
      replicas: 2
      resources:
        limits:
          cpus: '0.5'
          memory: 512M

  # Scheduler
  scheduler:
    image: cygnuzerp/app:latest
    container_name: cygnuz_scheduler
    restart: always
    command: /bin/sh -c "while true; do php artisan schedule:run --verbose --no-interaction & sleep 60; done"
    environment:
      APP_ENV: production
      DB_CONNECTION: mysql
      DB_HOST: "${DB_HOST}"
      DB_PORT: "${DB_PORT:-3306}"
      DB_DATABASE: "${DB_DATABASE}"
      DB_USERNAME: "${DB_USERNAME}"
      DB_PASSWORD: "${DB_PASSWORD}"
      REDIS_HOST: redis
      REDIS_PORT: 6379
      REDIS_PASSWORD: "${REDIS_PASSWORD}"
    volumes:
      - app_storage:/var/www/html/storage
    depends_on:
      - redis
    networks:
      - cygnuz_network
    deploy:
      resources:
        limits:
          cpus: '0.25'
          memory: 256M

networks:
  cygnuz_network:
    driver: bridge
    ipam:
      config:
        - subnet: 172.20.0.0/16

volumes:
  app_storage:
    driver: local
  app_logs:
    driver: local
  redis_data:
    driver: local