<?php

use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Swagger Documentation Routes
|--------------------------------------------------------------------------
|
| These routes are for accessing the API documentation generated by
| L5-Swagger. The documentation is available at /api/documentation
|
*/

// This file is intentionally empty as L5-Swagger handles its own routes
// The documentation will be available at the URL configured in config/l5-swagger.php