<?php

// Variables
return [
    'creatorName' => 'CZ App Studio',
    'creatorUrl' => 'https://czappstudio.com/',
    'supportNumber' => '++91 85902 11605',
    'supportWhatsappURL' => 'https://wa.me/+918590211605',
    'supportEmail' => 'support@czappstudio.com',
    'templateName' => 'Cygnuz ERP',
    'templateFullName' => 'Cygnuz ERP',
    'templateSuffix' => '',
    'templateVersion' => '0.1.0-alpha',
    'templateFree' => false,
    'templateDescription' => 'Cygnuz ERP is a comprehensive HR management system designed to streamline and automate various HR processes, including employee management, leave management, attendance tracking, payroll processing, recruitment, performance appraisal, training and development, expense management, task and project management, team collaboration, communication, notification management, workflow automation, reporting and analytics, and admin panel functionalities.',
    'templateKeyword' => 'hr, hr management, hr system, human resource management, employee management, leave management, attendance tracking, payroll processing, recruitment, performance appraisal, training and development, expense management, task management, project management, team collaboration, communication, notification management, workflow automation, reporting and analytics',
    'licenseUrl' => 'https://czappstudio.com/license/',
    'livePreview' => 'https://czappstudio.com',
    'productPage' => 'https://czappstudio.com',
    'support' => 'https://czappstudio.com/support/',
    'activationDocs' => 'https://czappstudio.com/docs/open-core-hr/product-activation/',
    'moreThemes' => 'https://czappstudio.com',
    'documentation' => 'https://czappstudio.com/docs/open-core-hr/',
    'changelog' => 'https://czappstudio.com',
    'repository' => 'https://czappstudio.com',
    'gitRepo' => 'https://czappstudio.com',
    'gitRepoAccess' => 'https://czappstudio.com',
    'githubFreeUrl' => 'https://czappstudio.com',
    'facebookUrl' => 'https://czappstudio.com',
    'twitterUrl' => 'https://czappstudio.com',
    'githubUrl' => 'https://czappstudio.com',
    'dribbbleUrl' => 'https://czappstudio.com',
    'instagramUrl' => 'https://www.instagram.com/czappstudio/',
    'linkedInUrl' => 'https://in.linkedin.com/company/cz-app-studio',
    'youtubeUrl' => 'https://www.youtube.com/@CZAppStudio',
    'superAdminPanelDemoLink' => 'https://opencorehr.czappstudio.com/',
    'adminPanelDemoLink' => 'https://opencorehr.czappstudio.com/',
];
